export enum QueryKeys {
  GET_ME = 'GET_ME',
  GET_DEPOSIT = 'GET_DEPOSIT',
  GET_DEPOSIT_V2 = 'GET_DEPOSIT_V2',
  GET_TOTAL_DEPOSIT_V2 = 'GET_TOTAL_DEPOSIT_V2',
  GET_GAME_HISTORY = 'GET_GAME_HISTORY',
  GET_USER_GAME_HISTORY = 'GET_USER_GAME_HISTORY',
  GET_WITHDRAWAL = 'GET_WITHDRAWAL',
  GET_WITHDRAWAL_V2 = 'GET_WITHDRAWAL_V2',
  GET_TOTAL_WITHDRAW_V2 = 'GET_TOTAL_WITHDRAW_V2',
  GET_WITHDRAWAL_TOTAL = 'GET_WITHDRAWAL_TOTAL',
  GET_VALIDATE_PASSWORD_HASH = 'GET_VALIDATE_PASSWORD_HASH',
  GET_STATS = 'GET_STATS',
  GET_USER_STATS = 'GET_USER_STATS',
  GET_USER_PROFIT_CHART = 'GET_USER_PROFIT_CHART',
  GET_USER_OVERVIEW = 'GET_USER_OVERVIEW',
  GET_MINIMUM_DEPOSITS = 'GET_MINIMUM_DEPOSITS',
  GET_LEADERBOARD = 'GET_LEADERBOARD',
  GET_NETWORK_INFO = 'GET_NETWORK_INFO',
  GET_NETWORK_AFFILIATES = 'GET_NETWORK_AFFILIATES',
}

export default QueryKeys
